In [1]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

from sklearn.svm import SVC
# import pickle

import joblib

In [2]:
dataset=pd.read_csv('Crop_recommendation.csv',header=None)
x=dataset.iloc[:,[0,3,4,5]].values
print(x)


[[ 90.          20.87974371  82.00274423   6.50298529]
 [ 85.          21.77046169  80.31964408   7.03809636]
 [ 60.          23.00445915  82.3207629    7.84020714]
 ...
 [118.          24.13179691  67.22512329   6.36260785]
 [117.          26.2724184   52.12739421   6.75879255]
 [104.          23.60301571  60.39647474   6.77983261]]


In [3]:
y=dataset.iloc[:,[7]].values
print(y)

[['rice']
 ['rice']
 ['rice']
 ...
 ['coffee']
 ['coffee']
 ['coffee']]


In [4]:
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# label_encoder = LabelEncoder()
# y = label_encoder.fit_transform(y)

y

array([['rice'],
       ['rice'],
       ['rice'],
       ...,
       ['coffee'],
       ['coffee'],
       ['coffee']], dtype=object)

In [5]:
xtest,xtrain,ytest,ytrain=train_test_split(x,y,test_size=0.3,random_state=100)

In [6]:
classifier=KNeighborsClassifier(n_neighbors=3,weights = 'uniform',algorithm = 'brute')
ytrain=np.ravel(ytrain)
classifier.fit(xtrain,ytrain)
# model=open("newknnmodel.pkl",'wb')
# pickle.dump(classifier,model)
# model.close()

joblib.dump(classifier,"newknnmodel.pkl")

['newknnmodel.pkl']

In [7]:
from sklearn.metrics import accuracy_score

In [8]:
ypred=classifier.predict(xtest)
score=accuracy_score(ytest,ypred)
print(f"Accuracy score of KNN = {score}")

Accuracy score of KNN = 0.7


In [9]:
classifier=tree.DecisionTreeClassifier(max_depth=3,min_samples_leaf=3)
ytrain=np.ravel(ytrain)
classifier.fit(xtrain,ytrain)
# model1=open("newdtmodel.pkl",'wb')
# pickle.dump(classifier,model1)
# model1.close()

joblib.dump(classifier,"newdtmodel.pkl")

['newdtmodel.pkl']

In [10]:
ypred=classifier.predict(xtest)
score=accuracy_score(ypred,ytest)
print(f"Accuracy score of Decision Tree = {score}")

Accuracy score of Decision Tree = 0.2597402597402597


In [11]:
classifier=SVC(kernel='rbf', random_state = 100)
ytrain=np.ravel(ytrain)
classifier.fit(xtrain,ytrain)

# model2=open("newsvmmodel.pkl",'wb')
# pickle.dump(classifier,model2)
# model2.close()

joblib.dump(classifier,"newsvmmodel.pkl")


['newsvmmodel.pkl']

In [12]:
ypred=classifier.predict(xtest)
score=accuracy_score(ypred,ytest)
print(f"Accuracy score of SVM = {score}")

Accuracy score of SVM = 0.5603896103896104


In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [14]:
classifier = RandomForestClassifier(n_estimators=100, random_state=42)

ytrain=np.ravel(ytrain)
classifier.fit(xtrain,ytrain)
# model2=open("randommodel.pkl",'wb')
# pickle.dump(classifier,model2)
# model2.close()

joblib.dump(classifier,"randommodel.pkl")


['randommodel.pkl']

In [ ]:
ypred=classifier.predict(xtest)
score=accuracy_score(ytest,ypred)
print(f"Accuracy score of RF = {score}")

Accuracy score of RF = 0.8480519480519481


In [ ]:
model=joblib.load("randommodel.pkl")

import numpy as np
testdata=np.array([[91,29.94,48.0,7.3]])

pred=model.predict(testdata)

print(pred)

['mothbeans']
